#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#            FishyLecterns by FlailoftheLord.                      #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#        For questions please join my discord server:              #
#               https://discord.gg/wuxW5PS                         #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------
# remember, you can assign the permission `fishylecterns.bypass` to allow a player to bypass any restrictions.
#-----------------------------------------------------------------

# Custom ID tag
# this is used to differentiate a fishy one from a normal Lectern.
# This is stored internally in the world's data and cannot be viewed 
# or modified in-game by a player.
LecternUUID: "fishy-lectern"

# the name of the item which you get via command.
LecternItemName: "&3Fishy&cLectern"

# Should players be able to drop books taken from a Fishy Lectern?
CanDropLecternBook: false

# Can a player have more than one book from a unique lectern in their inventory at one time?
CanHaveMultipleBooks: false

# have the player hear an errie noise when they take the book
BookRegenerateSound: ""

# Messages can be customized here
Prefix: "&8(&3&lF&c&lL&8)"
NoPermission: "%prefix% &cYou do not posess enough power to wield this!"
LecternPlaced: "%prefix% &aYou smell something &3&oFishy &r&aabout this &cLectern..."
LecternRemoved: "%prefix% &aYou have removed a great evil from this world!"
LecternItemGiven: "%prefix% &aYou just got a very &3&oFishy looking Lectern."
AlreadyHaveBook: "%prefix% &c&oThis book is too stubborn, it teleports back to the Lectern."
CannotDropBook: "%prefix% &e&oThe book magically springs back into your inventory!"
PluginReloaded: "%prefix% &3&lFishy&c&lLecterns &areloaded successfully!"
MustUseCommandInGame: "&cYou must use this command in-game!"

