#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#            FishyLecterns by FlailoftheLord.                      #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#        For questions please join my discord server:              #
#               https://discord.gg/wuxW5PS                         #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------
# remember, you can assign the permission `fishylecterns.bypass` to allow a player to bypass any restrictions.

# Custom ID tag
# this is used to differentiate a fishy one from a normal Lectern.
# This is stored internally on the Lectern Tile Entity and cannot be viewed 
# or modified in-game by a player without the use of mods/external tools.
# If you change this, any lecterns with the old ID will cease to work, you will have to replace them with new Lectern Items.
LecternUUID: "fishy-lectern"

# the name of the item which you get via command.
LecternItemName: "&3Fishy&cLectern"

# Should players be able to drop books taken from a Fishy Lectern?
CanDropLecternBook: false

# Maximum number of books from a unique lectern in a player's inventory at one time.
MaxLecternBooksInInventory: 1

NoPermission: "&cYou don't have permission for this!"